---
kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.92.0
    pull: always
    url: https://francocalvo.ar
    validate: true

