---
kind: pipeline
type: docker
name: default

steps:
- name: import theme
  image: alpine/git
  commands:
  - git submodule update --init

- name: install geekdocs theme
  pull: always
  image: node:16.14.0-alpine3.15
  commands:
  - npm install

- name: install mathjax support
  image: plugins/ansible:1
  settings:
    playbook: ansible/main.yaml

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.92.0
    pull: always
    url: https://francocalvo.ar
    validate: true

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 192.168.0.68
    user: dionisio
    port: 22
    password:
      from_secret: ssh_password
    target: /home/dionisio/services/config/swag/config/www
    source: public
    rm: true
    strip_components: 1
