---
kind: pipeline
type: docker
name: default

steps:
- name: import theme
  image: alpine/git
  commands:
  - git submodule update --init

- name: install theme
  pull: always
  image: node:16.14.0-alpine3.15
  commands:
  - npm install

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.92.0
    pull: always
    url: https://francocalvo.ar
    validate: true

